export const EXCLUDED_IDS = [
	"anterior",
	"arms-ligaments",
	"body-outline",
	"calcaneal-tendon",
	"elbow-ligament",
	"eyes",
	"hip-ligaments",
	"legs-ligaments",
	"ligamentum-nuchae",
	"muscles-anterior",
	"muscles-posterior",
	"popliteus",
	"posterior",
	"shin",
	"skin",
	"spinal-cord",
	"torso-midline",
	"tractus-iliotibialis",
	"tricep-deltoid-ligaments",
] as const;
